# Generated by Django 4.2.7 on 2024-01-07 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_review_body_alter_review_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 23, 31, 5, 329692)),
        ),
    ]
