# Generated by Django 4.2.7 on 2024-01-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_borrowbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='returnTime',
            field=models.DateTimeField(null=True),
        ),
    ]
