# Generated by Django 4.2.7 on 2024-01-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_borrowbook_returntime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
